version: "3.8"

services:
   app:
      build: .
      ports:
         - "3001:3001"
      environment:
         - DATABASE_URL=${DATABASE_URL}
         - PORT=${PORT}
         - JWT_SECRET_KEY=${JWT_SECRET_KEY}
         - MAIL_FROM=${MAIL_FROM}
         - MAIL_PASSWORD=${MAIL_PASSWORD}
         - FRONTEND_URL=${FRONTEND_URL}
      depends_on:
         - db

   db:
      image: postgres:16
      ports:
         - "54322:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}

volumes:
   postgres_data:
