services:
   nextpress-backend:
      container_name: nextpress-backend
      build: .
      ports:
         - "3001:3001"
      restart: always
      environment:
         - DATABASE_URL=${DATABASE_URL}
         - PORT=${PORT}
         - JWT_SECRET_KEY=${JWT_SECRET_KEY}
         - MAIL_FROM=${MAIL_FROM}
         - MAIL_PASSWORD=${MAIL_PASSWORD}
         - FRONTEND_URL=${FRONTEND_URL}
      depends_on:
         - nextpress-database
   nextpress-database:
      container_name: nextpress-database
      image: postgres:16
      ports:
         - "54322:5432"
      restart: always
      volumes:
         - nextpress-data:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}

volumes:
   nextpress-data:
